version: '3'

services:
  wallabag:
  #  image: wallabag/wallabag
    build: .
    ports:
    - 8111:80
    volumes:
    - ./parameters.yml:/var/www/wallabag/app/config/parameters.yml
    environment:
    - SYMFONY_ENV=prod
    - APACHE_DOCUMENT_ROOT=/var/www/wallabag/web

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=rah2Eeti
